# Generated by Django 3.2.3 on 2021-06-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message',
            name='room',
            field=models.CharField(default='0', max_length=1, verbose_name='Комната'),
        ),
    ]
